// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShortcutDeleter is an autogenerated mock type for the ShortcutDeleter type
type ShortcutDeleter struct {
	mock.Mock
}

// DeleteURL provides a mock function with given fields: alias
func (_m *ShortcutDeleter) DeleteURL(alias string) error {
	ret := _m.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShortcutDeleter creates a new instance of ShortcutDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortcutDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortcutDeleter {
	mock := &ShortcutDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
